name: whisker_garden
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.25.1
  drift_postgres: ^1.3.0
  postgres: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.25.2
  build_runner: ^2.4.15

flutter:
  uses-material-design: true


