name: whisker_garden
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.25.1
  drift_postgres: ^1.3.0
  sqlite3_flutter_libs: ^0.5.30
  path_provider: ^2.0.2
  path: ^1.8.0
  get_it: ^7.6.0 
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.25.2
  build_runner: ^2.4.15

flutter:
  uses-material-design: true


